<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $config->locale; ?>">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	
	<title><?php echo $title; ?> / <?php echo $site_name; ?></title>
	
	<base href="<?php echo $config->url; ?>" />
	<!-- <link rel="canonical" href="post/2" /> -->
	
	<link rel="alternate" type="application/rss+xml" title="<?php echo $site_name; ?> RSS Feed" href="feed" />
	<link rel="stylesheet" href="content/themes/greyspace_neue/styles/dark.css" type="text/css" charset="utf-8" title="Dark" />
	<link rel="alternate stylesheet" href="content/themes/greyspace_neue/styles/light.css" type="text/css" charset="utf-8" title="Light" />
	<style type="text/css">
	
		<?php if (isset($posts['current']->width)): ?>
			.section{
				width: <?php echo $posts['current']->width; ?> px;
			}
		<?php endif ?>
	
	</style>
	<?php Pixelpost_Plugin::executeAction('hook_page_head');  ?>
</head>

<body>

<?php echo $content ?>

<?php Pixelpost_Plugin::executeAction('hook_page_body');  ?>
</body>
</html>