<h1>Welcome to WEB2BB</h1>

<p>
WEB2BB brings the power of PHP 5.3 and PHP 6 to application development. Now you can develop a site very quickly that is easy to maintain and uses the latest cutting edge tools from the PHP toolbox.
<p>

<p>
WEB2BB does not try to be all things to all people, and so, avoid much of the mindless bloat that pollute other frameworks. WEB2BB does not even care what the others are doing, it stands alone as a light weight, yet powerful tool to make application and web site development fast and easy.
</p>

<p>
Like any PHP MVC framework, WEB2BB provides the seperation of logic demanded today from those who need a maintainable system.
</p>

<p>
At this stage of development, no functional requests are being taken, if there is a feature you think would be good, submit a patch, dont whine about it not being there.
</p>
