<?php

@header($_SERVER["SERVER_PROTOCOL"]." 404 Not Found");

?><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
	<title>Error <?php echo $e->getCode(); ?></title>
	
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	
	<style type="text/css">
		* {
			padding: 0px;
			margin: 0px;
		}
		body {
			background: #FAFAFA;
			color: #444;
			font: normal 0.9em "Lucida Sans Unicode",sans-serif;
		}
		a {
			color: #4283B9;
			text-decoration: none;
		}
		a:hover {
			color: #111;
		}
		h1 {
			color: #333;
			font: normal 1.4em/24px Verdana,sans-serif;
			padding-bottom: 5px;
		}
		p,code,em,ul {
			
			padding: 5px 0;
		}
		#content {
			width: 700px;
			text-align: center;
			margin: 50px auto 0;
		}
		#content .item {
			text-align: left;
			padding: 6px 12px;
			border: 1px solid #EEE;
			background: #FFF;
		}
	</style>
</head>

<body>

<div id="container">
	
	<div id="content">
		
		<div class="item">
			<h1>Whoops!</h1>
			
			<p>We can't seem to find the page you specified. It's possible the page has been moved, or no longer exists.</p>
			
			<p>Please try visiting the <a href="<?php echo $config->url; ?>">home page</a>.</p>
			
		</div>
		
	</div>
	
</div>

</body>
</html>