<div id="wrapper">

	<div class="top section">
		<span class="published">Archive</span>
		<h1 class="title"><?php echo $title; ?></h1>
		<div class="nav"><a href="./">Home</a> <a href="archive" class="active">Archive</a> <a href="about">About</a></div>
		<br class="clear"/>
	</div>

	
	<div class="middle section">
		
		
		<div class="thumbnails section">
			<?php echo $thumbnails; ?>
		</div>
		
		<div class="site section">
			<h2 class="name"><a href="./" title="View Latest Photo"><?php echo $site_name; ?></a></h2>
			<em class="tagline"><?php echo $site_description; ?></em>
		</div>
	</div>
	
	<div class="bottom section">
		
		<?php if ($config->posts_per_page): ?>
		
			<div class="pagination">
				
				<?php if ((WEB2BB_Uri::$page) == 2): ?>
					<a href="<?php echo WEB2BB_Uri::$uri; ?>" class="previous">&#x2190; Previous Page</a>

				<?php elseif ((WEB2BB_Uri::$page) > 1): ?>
					<a href="<?php echo WEB2BB_Uri::$uri . '/page/' . (WEB2BB_Uri::$page-1); ?>" class="previous">&#x2190; Previous Page</a>
					
				<?php else: ?>
					<a class="previous disabled">&#x2190; Previous Page</a>
					
				<?php endif ?>
				
				
				<?php if (WEB2BB_Uri::$page < WEB2BB_Uri::$total_pages): ?>
					<a href="<?php echo WEB2BB_Uri::$uri . '/page/' . (WEB2BB_Uri::$page+1); ?>" class="next">Next Page &#x2192;</a>
					
				<?php else: ?>
					<a class="next disabled">Next Page &#x2192;</a>
					
				<?php endif ?>
				
				
				<span class="page"><?php echo "Page " . WEB2BB_Uri::$page . " of " . WEB2BB_Uri::$total_pages; ?></span>
			
				<br class="clear"/>
			</div>
		
		<?php endif ?>
		
		<?php if (!empty($categories)): ?>
			<h3>Categories</h3>
			<div class="categories">
				<?php foreach ($categories as $category): ?>
					<?php if ($category->depth == 0 || $category->depth > 1) continue; ?>
					<li><a href="<?php echo "archive/category/".strtolower($category->name); ?>"><?php echo htmlentities($category->name); ?></a></li>
				<?php endforeach ?>
			</div>
		<?php endif ?>
		
		<?php if (!empty($tags)): ?>
			<h3>Tags</h3>
			<div class="tags">
				<?php foreach ($tags as $tag): ?>
					<li><a href="<?php echo "archive/tag/".rawurlencode(strtolower($tag->name)); ?>"><?php echo htmlentities($tag->name); ?></a></li>
				<?php endforeach ?>
			</div>
		<?php endif ?>

		
	</div>

</div>
