<div id="wrapper">

	<div class="top section">
		<span class="published"><?php echo $posts['current']->published; ?></span>
		<h1 class="title"><?php echo $title; ?></h1>
		<div class="nav"><a href="./" class="active">Home</a> <a href="archive">Archive</a> <a href="about">About</a></div>
		<br class="clear"/>
	</div>

	<div class="middle section">
		<a href="<?php echo $posts['next']->permalink; ?>"><img src="<?php echo $posts['current']->uri; ?>" alt="<?php echo $posts['current']->title; ?>" width="<?php echo $posts['current']->width; ?>" height="<?php echo $posts['current']->height; ?>" id="photo" /></a>
		<div class="site section">
			<h2 class="name"><a href="./" title="View Latest Photo"><?php echo $site_name; ?></a></h2>
			<em class="tagline"><?php echo $site_description; ?></em>
		</div>
	</div>


	<div class="bottom section">
		<div id="description">
			<?php echo $posts['current']->description; ?>
		</div>
	</div>

</div>
