<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
	<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
	<title><?php echo $title; ?></title>
	<link rel="stylesheet" href="<?php echo __PUBLIC_PATH; ?>/css/style.css">
	<base href="/<?php echo __PUBLIC_PATH; ?>/" />
</head>

<body>

<div id="container">

<div id="top">
<h1>WEB2BB</h1>
</div>

<div id="leftnav">
<ul>
<li><a href="./"><?php echo lang::__HOME; ?></a></li>
<li><a href="blog"><?php echo lang::__BLOG; ?></a></li>
<li><a href="docs"><?php echo lang::__DOCS; ?></a></li>
<li><a href="contact"><?php echo lang::__CONTACT; ?></a></li>
<li><a href="#">LINK</a></li>
<li><a href="#">LINK</a></li>
<li><a href="#">LINK</a></li>
</ul>
</div>

<div id="content">

<?php echo $content; ?>

</div>

<div id="footer">
Powered By <a href="http://web2bb.com">WEB2BB <?php echo $version; ?></a>
</div>

</div>

</body>
</html>
